[build]
buildCommand = "bun install && bun run build"
startCommand = "bun run start"

[env]
NODE_ENV = "production"
PORT = "3000"

[phases]
setup = "bun install"
build = "bun run build"
start = "bun run start"

[scripts]
postinstall = "bun run build"

[metadata]
name = "web-plugin-hukusis"
description = "Web Search Plugin for Hukusis"
version = "1.0.0" 